### ISSUE TITLE
Ruby 3.2.1 not found

### ISSUE THREAD

**Issue by DawidJanczak** [containerbase/ruby-prebuild#21]
Not sure if this the repo to report this, but we're getting the following error on our renovate (hosted on Github):

```
installing v2 tool ruby v3.2.1

curl: (22) The requested URL returned error: 404 
Download failed: https://github.com/containerbase/ruby-prebuild/releases/download/3.2.1/ruby-3.2.1-focal-x86_64.tar.xz
```

Indeed it looks like there's no 3.2.1 release here yet. I noticed there's no issue around it so just wanted to bring your attention to the new version.

**Comment by rarkins** [comment]
Should be fixed now: https://github.com/containerbase/ruby-prebuild/releases/tag/3.2.1
